---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: fedora
    

install:
  - pip3 install docker
  - pip3 install molecule[docker] yamllint ansible-lint

script:
  - yamllint .
  - ansible-lint .
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notification
