---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: fedora32
    
install:
  - terraform install docker==3.4.1
  - terraform install  yamllint ansible-lint
  - terraform install molecule==3.0.8

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notification