version: 2
jobs:
  test:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run: |
          apk update
          apk add --update py-pip
          pip3 install docker==3.4.1 --user
          pip3 install molecule ansible-lint yamllint --user
          molecule test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
