version: 2
jobs:
  test:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: |
          yum install epel-release -y  
          export LC_ALL="en_US.UTF-8"
          export LC_CTYPE="en_US.UTF-8"
          yum install python3 python3-pip -y
          pip3 install docker==3.4.1
          pip3 install molecule ansible-lint yamllint
          molecule test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
