version: 2
jobs:
  test:
    machine:
      services: docker
    steps:
      - checkout
      - run: |
          apt update 
          apt install python3.8
          apt install python3-pip
          pip install --upgrade pip
          pip install docker==3.4.1
          pip install molecule ansible-lint yamllint
          molecule test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
