version: 2
jobs:
  test:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: |
          yum install epel-release -y
          yum install python3 python3-pip
          pip3 install docker==3.4.1
          pip3 install molecule ansible-lint yamllint
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
