version: 2
jobs:
  test:
    machine:
      services: docker
    environment:
      - DISTRO: centos8
      - DISTRO: centos7
      - DISTRO: centos6
      - DISTRO: ubuntu1804
      - DISTRO: ubuntu1604
      - DISTRO: debian10
      - DISTRO: debian9
    steps:
      - checkout
      - run: |
          sudo apt update
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python3.8
          sudo apt install pyMOLECULE_DISTROthon3-pip
          pip3 install --upgrade pip
          pip3 install docker==3.4.1
          pip3 install molecule ansible-lint yamllint
          mkdir ~/ansible-role-terraform
          mv ~/project/ ~/ansible-role-terraform
          cd ~/ansible-role-terraform          
          ls -la -F
          MOLECULE_DISTRO=$DISTRO molecule test      
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
