version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run: |
          pip3 install docker==3.4.1 --user
          pip3 install molecule ansible-lint yamllint --user
          molecule test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
