version: 2
jobs:
  test:
    machine:
      services: docker
    environment:
      - MOLECULE_DISTRO: centos8
      - MOLECULE_DISTRO: centos7
      - MOLECULE_DISTRO: centos6
      - MOLECULE_DISTRO: ubuntu1804
      - MOLECULE_DISTRO: ubuntu1604
      - MOLECULE_DISTRO: debian10
      - MOLECULE_DISTRO: debian9
    steps:
      - checkout
      - run: |
          sudo apt update 
          sudo apt install python3
          sudo apt install python3-pip
          pip3 install --upgrade pip
          pip3 install docker==3.4.1
          pip3 install molecule ansible-lint yamllint
          mkdir ~/ansible-role-terraform
          mv ~/project/ ~/ansible-role-terraform
          cd ~/ansible-role-terraform          
          ls -la -F
          molecule test      
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
