version: 2
jobs:
  test:
    machine:
      services: docker
    environment:
      - ROLE_NAME: terraform
    steps:
      - checkout
      - run: |
          sudo apt-get update -y
          sudo apt-get install python -y
          sudo apt-get install python-pip -y
          pip install --upgrade pip
          
      - run: |
          pip install docker==3.4.1
          pip install molecule ansible-lint yamllint
          
      - run: |
          mkdir ~/ansible-role-$ROLE_NAME
          cd ..
          mv ~/project/{,.[^.]}* ~/ansible-role-$ROLE_NAME
          cd ~/ansible-role-$ROLE_NAME
          molecule test      
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
