version: 2
jobs:
  test:
    machine:
      services: docker
    steps:
      - checkout
      - run: |
          sudo apt update 
          sudo apt install python3
          sudo apt install python3-pip
          pip install --upgrade pip
          pip install docker==3.4.1
          pip install molecule ansible-lint yamllint
          mkdir ~/ansible-role-terraform
          mv ~/project/ ~/ansible-role-terraform
          cd ~ansible-role-terraform
          molecule test      
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
