version: 2
jobs:
  build:
    docker:
      - image: ansible/ansible:centos7
    steps:
      - checkout
      - run: |
          cat $HOME/.ssh/id_rsa.pub >> $HOME/.ssh/authorized_keys
          cd install_terraform
          ansible-playbook deploy_terraform.yaml -e "terraform_version=0.12.23"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
