version: 2
jobs:
  test:
    machine:
      services: docker
    steps:
      - checkout
      - run: |
          pip install --upgrade pip
          pip install docker==3.4.1 --user
          pip install molecule ansible-lint yamllint --user
          ls -la -F
          uname -a
          molecule test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
